### ISSUE TITLE
Implement loop keyword euqivalent for "break" and "continue"

### ISSUE THREAD

**Issue by iSlinger** [Mellow-Programming-Language/Mellow#43]
Allows for easier loop control in the case of a quick exit or to skip forward to the next loop iteration.

The keywords need not be "break" and "continue." Alternate examples:

break: exit, escape, cancel...

continue: next, skip, proceed...

Related (or duplicate of) #32

**Comment by iSlinger** [comment]
Related (or duplicate of)  #32

**Comment by CollinReeser** [comment]
The implementation of `break` is tracked by Issue #32. Implementation of `continue` will be tracked by this issue.

**Comment by CollinReeser** [comment]
Implemented.
