### ISSUE TITLE
Implement "for" loop structure

### ISSUE THREAD

**Issue by iSlinger** [Mellow-Programming-Language/Mellow#44]
Currently a for loop is written in the following manner:

```
i := 0;
while (i < value)
{
    //loop
    i = i + 1;
}
```

In the current implementation, the following is also valid syntax:

```
while (i := 0; i < value)
{
    //loop
    i = i + 1;
}
```

It would be nice to be able to have the loop's counter and increment step be declared on a single line with its quit condition.

**Comment by CollinReeser** [comment]
Implemented with commit 72a89d8d9d82f516f8076b24dbe07cf77258bcd7.
